<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 a = 1;</code>
     */
    private $a = 0;
    /**
     * Generated from protobuf field <code>int64 b = 2;</code>
     */
    private $b = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $a
     *     @type int|string $b
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 a = 1;</code>
     * @return int|string
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * Generated from protobuf field <code>int64 a = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setA($var)
    {
        GPBUtil::checkInt64($var);
        $this->a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 b = 2;</code>
     * @return int|string
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Generated from protobuf field <code>int64 b = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setB($var)
    {
        GPBUtil::checkInt64($var);
        $this->b = $var;

        return $this;
    }

}

