<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad4010a0d736572766963652e70726f746f120570726f746f221f0a0752" .
            "65717565737412090a016118012001280312090a0162180220012803221a" .
            "0a08526573706f6e7365120e0a06726573756c7418012001280332610a0a" .
            "4164645365727669636512260a03416464120e2e70726f746f2e52657175" .
            "6573741a0f2e70726f746f2e526573706f6e7365122b0a084d756c746970" .
            "6c79120e2e70726f746f2e526571756573741a0f2e70726f746f2e526573" .
            "706f6e736542145a12646963686f6964692e636f6d2f70726f746f620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

